replacement="scopes = [\"mt\", \"et\"]"
sed -i '/^scopes = /c\'"$replacement" "lawluigi_configs/KingMaker_lxplus_luigi.cfg"


nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_ggh_htautau.txt  --workers 1 --production-tag NanoV12_2022MC_ggh_htautau${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_ggh_htautau${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_vbf_htautau.txt  --workers 1 --production-tag NanoV12_2022MC_vbf_htautau${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_vbf_htautau${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_dyjets.txt  --workers 1 --production-tag NanoV12_2022MC_dyjets${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_dyjets${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_diboson.txt  --workers 1 --production-tag NanoV12_2022MC_diboson${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_diboson${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_ttbar.txt  --workers 1 --production-tag NanoV12_2022MC_ttbar${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_ttbar${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_singletop.txt  --workers 1 --production-tag NanoV12_2022MC_singletop${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_singletop${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_htautau.txt  --workers 1 --production-tag NanoV12_2022MC_htautau${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_htautau${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2022MC_wjets.txt  --workers 1 --production-tag NanoV12_2022MC_wjets${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2022MC_wjets${channel}_Version11_allsyst.log & 




nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_ggh_htautau.txt  --workers 1 --production-tag NanoV12_2023MC_ggh_htautau${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_ggh_htautau${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_vbf_htautau.txt  --workers 1 --production-tag NanoV12_2023MC_vbf_htautau${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_vbf_htautau${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_dyjets.txt  --workers 1 --production-tag NanoV12_2023MC_dyjets${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_dyjets${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_singletop.txt  --workers 1 --production-tag NanoV12_2023MC_singletop${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_singletop${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_diboson.txt  --workers 1 --production-tag NanoV12_2023MC_diboson${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_diboson${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_ttbar.txt  --workers 1 --production-tag NanoV12_2023MC_ttbar${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_ttbar${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_htautau.txt  --workers 1 --production-tag NanoV12_2023MC_htautau${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_htautau${channel}_Version11_allsyst.log & 
nohup law run ProduceSamples --local-scheduler False --analysis tau  --config config --sample-list sample_database/Htautau_input_list/NanoV12_2023MC_wjets.txt  --workers 1 --production-tag NanoV12_2023MC_wjets${channel}_Version11_allsyst >> KingMaker_logs/NanoV12_2023MC_wjets${channel}_Version11_allsyst.log & 